locallibrary/urls.py
from django.urls import path
from django.contrib import admin
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('management/', include('management.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='/management/', permanent=True)),
    path('', include('management.urls')),
]

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

management/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from . import views
from .views import *

router = DefaultRouter()
router.register(r'categories', CategoryViewSet)
router.register(r'warehouses', WarehouseViewSet)
router.register(r'products', ProductViewSet)
router.register(r'orders', OrderViewSet)
router.register(r'deliveries', DeliveryViewSet)
router.register(r'suppliers', SupplierViewSet)

urlpatterns = [
    path('', views.index, name='index'),

    path('api/', include(router.urls)),

    path('warehouses/', WarehouseListView.as_view(), name='warehouse-list'),
    path('orders/', OrderListView.as_view(), name='order-list'),
    path('deliveries/', DeliveryListView.as_view(), name='delivery-list'),
    path('suppliers/', SupplierListView.as_view(), name='supplier-list'),

    path('warehouse/', views.WarehouseListView.as_view(), name='warehouse-list'),
    path('warehouse/<int:pk>/', views.WarehouseDetailView.as_view(), name='warehouse-detail'),
    path('order/', views.OrderListView.as_view(), name='order-list'),
    path('order/<int:pk>/', views.OrderDetailView.as_view(), name='order-detail'),
    path('delivery/', views.DeliveryListView.as_view(), name='delivery-list'),
    path('delivery/<int:pk>/', views.DeliveryDetailView.as_view(), name='delivery-detail'),
    path('supplier/', views.SupplierListView.as_view(), name='supplier-list'),
    path('supplier/<int:pk>/', views.SupplierDetailView.as_view(), name='supplier-detail'),

    path('product/', views.ProductListView.as_view(), name='product'),
    path('product/<int:pk>', views.ProductDetailView.as_view(), name='product-detail'),
    path('category/', views.CategoryListView.as_view(), name='category'),
    path('category/<int:pk>', views.CategoryDetailView.as_view(), name='category-detail'),
    path('product/', ProductListView.as_view(), name='products'),
    path('product/<int:pk>/', ProductDetailView.as_view(), name='product-detail'),
    path('product/create/', ProductCreateView.as_view(), name='product-create'),
    path('product/<int:pk>/update/', ProductUpdateView.as_view(), name='product-update'),
    path('product/<int:pk>/delete/', ProductDeleteView.as_view(), name='product-delete'),
    path('categories/', CategoryListView.as_view(), name='categories'),
    path('category/<int:pk>/', CategoryDetailView.as_view(), name='category-detail'),
    path('category/create/', CategoryCreateView.as_view(), name='category-create'),
    path('category/<int:pk>/update/', CategoryUpdateView.as_view(), name='category-update'),
    path('category/<int:pk>/delete/', CategoryDeleteView.as_view(), name='category-delete'),
    path('warehouses/', WarehouseListView.as_view(), name='warehouses'),
    path('warehouse/<int:pk>/', WarehouseDetailView.as_view(), name='warehouse-detail'),
    path('warehouse/create/', WarehouseCreateView.as_view(), name='warehouse-create'),
    path('warehouse/<int:pk>/update/', WarehouseUpdateView.as_view(), name='warehouse-update'),
    path('warehouse/<int:pk>/delete/', WarehouseDeleteView.as_view(), name='warehouse-delete'),
    path('orders/', OrderListView.as_view(), name='orders'),
    path('order/<int:pk>/', OrderDetailView.as_view(), name='order-detail'),
    path('order/create/', OrderCreateView.as_view(), name='order-create'),
    path('order/<int:pk>/update/', OrderUpdateView.as_view(), name='order-update'),
    path('order/<int:pk>/delete/', OrderDeleteView.as_view(), name='order-delete'),
    path('deliveries/', DeliveryListView.as_view(), name='deliveries'),
    path('delivery/<int:pk>/', DeliveryDetailView.as_view(), name='delivery-detail'),
    path('delivery/create/', DeliveryCreateView.as_view(), name='delivery-create'),
    path('delivery/<int:pk>/update/', DeliveryUpdateView.as_view(), name='delivery-update'),
    path('delivery/<int:pk>/delete/', DeliveryDeleteView.as_view(), name='delivery-delete'),
    path('suppliers/', SupplierListView.as_view(), name='suppliers'),
    path('supplier/<int:pk>/', SupplierDetailView.as_view(), name='supplier-detail'),
    path('supplier/create/', SupplierCreateView.as_view(), name='supplier-create'),
    path('supplier/<int:pk>/update/', SupplierUpdateView.as_view(), name='supplier-update'),
    path('supplier/<int:pk>/delete/', SupplierDeleteView.as_view(), name='supplier-delete'),
]

management/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from simple_history.models import HistoricalRecords


class Category(models.Model):
    name = models.CharField(max_length=200, help_text="Введите название категории товара")
    summary = models.TextField(max_length=1000, help_text="Введите краткое описание категории")

    history = HistoricalRecords()
    def get_absolute_url(self):
        return reverse('category-detail', args=[str(self.id)])

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'


class Category_Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    product = models.ForeignKey("Product", on_delete=models.CASCADE)
    history = HistoricalRecords()
    def __str__(self):
        return f"{self.category} - {self.product}"

    class Meta:
        verbose_name = 'Category_Product'
        verbose_name_plural = 'Categories_Products'


class Warehouse(models.Model):
    name = models.CharField(max_length=200, help_text="Введите название склада")
    address = models.CharField(max_length=200, help_text="Введите адрес склада")
    history = HistoricalRecords()
    def get_absolute_url(self):
        return reverse('warehouse-detail', args=[str(self.id)])

    def __str__(self):
        return self.name


class ProductWarehouse(models.Model):
    product = models.ForeignKey("Product", on_delete=models.CASCADE)
    warehouse = models.ForeignKey(Warehouse, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(help_text="Введите количество товара на складе", default=0)
    history = HistoricalRecords()
    def __str__(self):
        return f"{self.product} - {self.warehouse}"

    class Meta:
        verbose_name = 'ProductWarehouse'
        verbose_name_plural = 'ProductWarehouses'


class Product(models.Model):
    name = models.CharField(max_length=200, help_text="Введите название товара")
    summary = models.CharField(max_length=1000, help_text="Введите краткое описание товара")
    price = models.DecimalField(max_digits=10, decimal_places=2, help_text="Введите цену товара")
    quantity = models.PositiveIntegerField(help_text="Введите количество товара")
    warehouses = models.ManyToManyField(Warehouse, through=ProductWarehouse, related_name='products', help_text="Склады", blank=True)
    categories = models.ManyToManyField(Category, through=Category_Product, related_name='products', help_text="Категории", blank=True)
    history = HistoricalRecords()
    def get_absolute_url(self):
        return reverse('product-detail', args=[str(self.id)])

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        warehouses = self.warehouses.all()
        for warehouse in warehouses:
            ProductWarehouse.objects.update_or_create(
                product=self,
                warehouse=warehouse,
                defaults={'quantity': self.quantity}
            )


class Order(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(help_text="Введите количество товара")
    date = models.DateField(auto_now_add=True, help_text="Время создания заказа")
    STATUS_CHOICES = (
        ('PENDING', 'Pending'),
        ('PROCESSING', 'Processing'),
        ('SHIPPED', 'Shipped'),
        ('DELIVERED', 'Delivered'),
        ('CANCELLED', 'Cancelled'),
    )
    status = models.CharField(max_length=100, choices=STATUS_CHOICES)
    history = HistoricalRecords()

    def get_absolute_url(self):
        return reverse('order-detail', args=[str(self.id)])

    def __str__(self):
        return str(self.product)


class Delivery(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    supplier = models.ForeignKey("Supplier", on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(help_text="Введите количество поставляемого товара")
    date = models.DateField(help_text="Выберите дату поставки")
    history = HistoricalRecords()

    def get_absolute_url(self):
        return reverse('delivery-detail', args=[str(self.id)])

    def __str__(self):
        return str(self.product)

    class Meta:
        verbose_name = 'Delivery'
        verbose_name_plural = 'Deliveries'


class Supplier(models.Model):
    name = models.CharField(max_length=200, help_text="Введите наименование организации")
    contact = models.CharField(max_length=200, help_text="Введите контактное лицо")
    address = models.CharField(max_length=200, help_text="Введите адрес поставщика")
    tel = models.CharField(max_length=20, help_text="Введите номер телефона")
    history = HistoricalRecords()

    def get_absolute_url(self):
        return reverse('supplier-detail', args=[str(self.id)])

    def __str__(self):
        return self.name

management/forms.py
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
import datetime  # for checking renewal date range.
from django import forms

management/templates/management/category_detail.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Категория: {{ category }} </h1>
<p>{{category.summary}}</p>

{% endblock %}

management/templates/management/category_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Список категорий:</h1>

    {% if category_list %}
        <ul>
            {% for category in category_list %}
                <li>
                    <a href="{{ category.get_absolute_url }}">
                        {{ category.name }}
                    </a>
                    {% with category_products=category.category_product_set.all %}
                        {% if category_products %}
                            <ul>
                                {% for category_product in category_products %}
                                    <li>
                                        <a href="{{ category_product.product.get_absolute_url }}">
                                            {{ category_product.product.name }}
                                        </a>
                                    </li>
                                {% endfor %}
                            </ul>
                        {% else %}
                            <p>Нет товаров в данной категории.</p>
                        {% endif %}
                    {% endwith %}
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>Не существует ни одной категории.</p>
    {% endif %}
{% endblock %}

management/templates/management/delivery_detail.html
{% extends "base_generic.html" %}
{% block content %}
{% if user.is_staff %}
<h1>Поставка: {{ delivery.title }}</h1>
<p><strong>Товар:</strong> <a href="{{ delivery.get_absolute_url }}">{{ delivery.name }}</a></p>
<p><strong>Поставщик:</strong> {{ delivery.supplier }}</p>
<p><strong>Количество:</strong> {{ delivery.quantity }}</p> 
<p><strong>Дата поставки:</strong> {{ delivery.date }}</p> 
{% endif %}
{% endblock %}

management/templates/management/delivery_list.html
{% extends "base_generic.html" %}

{% block content %}
{% if user.is_staff %}
    <h1>Список поставок:</h1>
    {% if delivery_list %}
        <ul>
        {% for delivery in delivery_list %}
            <li>
                <a href="{{ delivery.get_absolute_url }}">
                    {{ delivery.product }} - ({{ delivery.supplier }})
                </a>
            </li>
        {% endfor %}
        </ul>
    {% else %}
        <p>Нет доступных поставок.</p>
    {% endif %}
{% else %}
    <p>У вас нет доступа к этой странице. Пожалуйста, войдите под учетной записью с правами доступа.</p>
{% endif %}
{% endblock %}

management/templates/management/order_detail.html
{% extends "base_generic.html" %}
{% block content %}
{% if user.is_staff %}
<h1>Заказ: {{ order.title }}</h1>
<p><strong>Товар:</strong> <a href="{{ order.get_absolute_url }}">{{ order.product }}</a></p>
<p><strong>Клиент:</strong> {{ order.user }}</p>
<p><strong>Количество:</strong> {{ order.quantity }}</p> 
<p><strong>Дата заказа:</strong> {{ order.date }}</p> 
<p><strong>Статус заказа:</strong> {{ order.status }}</p> 
{% endif %}
{% endblock %}

management/templates/management/order_list.html
{% extends "base_generic.html" %}

{% block content %}
{% if user.is_staff %}
    <h1>Список заказов:</h1>
    {% if order_list %}
        <ul>
        {% for order in order_list %}
            <li>
                <a href="{{ order.get_absolute_url }}">
                    {{ order.product }} - ({{ order.user }}) - ({{ order.status }})
                </a>
            </li>
        {% endfor %}
        </ul>
    {% else %}
        <p>Нет доступных заказов.</p>
    {% endif %}
{% else %}
    <p>У вас нет доступа к этой странице. Пожалуйста, войдите под учетной записью с правами доступа.</p>
{% endif %}
{% endblock %}

management/templates/management/product_detail.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Товар: {{ product.title }}</h1>

<p><strong>Название:</strong> <a href="{{ product.categoty.get_absolute_url }}">{{ product.name }}</a></p>
<p><strong>Информация:</strong> {{ product.summary }}</p>
<p><strong>Цена:</strong> {{ product.price }}$</p> 
<p><strong>Количество:</strong> {{ product.quantity }}</p> 


{% endblock %}

management/templates/management/product_list.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Список товаров:</h1>

{% if product_list %}
  <ul>

  {% for product in product_list %}
    <li>
      <a href="{{ product.get_absolute_url }}">
        {{ product }}
      </a>
    </li>
  {% endfor %}

 </ul>
{% else %}
  <p>Нет товаров в наличии.</p>
{% endif %}
        
        
        
{% endblock %}

management/templates/management/supplier_detail.html
{% extends "base_generic.html" %}
{% block content %}
{% if user.is_staff %}
<h1>Поставщик: {{ supplier.title }}</h1>
<p><strong>Наименование организации:</strong> <a href="{{ supplier.get_absolute_url }}">{{ supplier.name }}</a></p>
<p><strong>Контактное лицо:</strong> {{ supplier.contact }}</p>
<p><strong>Адрес поставщика:</strong> {{ supplier.address }}</p> 
<p><strong>Контактный телефон:</strong> {{ supplier.tel }}</p> 
{% endif %}
{% endblock %}

management/templates/management/supplier_list.html
{% extends "base_generic.html" %}

{% block content %}
{% if user.is_staff %}
    <h1>Список поставщиков:</h1>
    {% if supplier_list %}
        <ul>
        {% for supplier in supplier_list %}
            <li>
                <a href="{{ supplier.get_absolute_url }}">{{ supplier.name }}</a>
            </li>
        {% endfor %}
        </ul>
    {% else %}
        <p>Нет доступных поставщиков.</p>
    {% endif %}
{% else %}
    <p>У вас нет доступа к этой странице. Пожалуйста, войдите под учетной записью с правами доступа.</p>
{% endif %}
{% endblock %}

management/templates/management/warehouse_detail.html
{% extends "base_generic.html" %}

{% block content %}
{% if user.is_staff %}
    <h1>Склад: {{ warehouse.title }}</h1>
    <p><strong>Название склада:</strong> {{ warehouse.name }}</p>
    <p><strong>Адрес склада:</strong> {{ warehouse.address }}</p>
    <p><strong>Товары:</strong></p>
    <ul>
        {% for product in warehouse.products.all %}
            <li><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></li>
        {% empty %}
            <li>Нет товаров на складе</li>
        {% endfor %}
    </ul>
{% endif %}
{% endblock %}

management/templates/management/warehouse_list.html
{% extends "base_generic.html" %}

{% block content %}
{% if user.is_staff %}
    <h1>Список складов:</h1>
    {% if warehouse_list %}
        <ul>
        {% for warehouse in warehouse_list %}
            <li>
                <a href="{{ warehouse.get_absolute_url }}">{{ warehouse.name }}</a>
            </li>
        {% endfor %}
        </ul>
    {% else %}
        <p>Нет доступных складов.</p>
    {% endif %}
{% else %}
    <p>У вас нет доступа к этой странице. Пожалуйста, войдите под учетной записью с правами доступа.</p>
{% endif %}
{% endblock %}